name: Upload to Dropbox

on:
  push:
    paths:
      - 'data/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to Dropbox
        uses: jaxxstorm/action-upload-to-dropbox@v1.2.1
        with:
          dropbox_token: ${{ secrets.DROPBOX_TOKEN }}
          dropbox_path: /ResearchObs/
          local_path: ./data/
